import { allRows, rpc } from '../services/data.js';
import { supabase } from '../supabase.js';
import { heading, e, table, field, options, openEditor, notice, loadError } from '../components/ui.js';

export async function receptionsPage(root, access) {
 let rows=[], providers=[], products=[], sites=[], lots=[];
 const canWrite=access.rol!=='consulta';
 root.innerHTML=heading('Recepciones','Registra compras, diferencias entre factura y entrega y sus comprobantes.',canWrite?'<button id="new-reception" class="button primary">+ Nueva recepción</button>':'')+'<section class="panel"><div class="toolbar"><button id="refresh" class="button">Actualizar</button></div><div id="results"></div></section>';
 function render(){root.querySelector('#results').innerHTML=table(['Fecha','Proveedor','Comprobante','Sede','Productos','Facturado','Recibido','Faltante','Responsable','Adjuntos'],rows.map(r=>[e(r.fecha_emision),e(r.proveedor),e((r.tipo_comprobante||'Factura')+' '+r.serie+'-'+r.numero),e(r.sede),e(r.productos),e(r.facturado),e(r.recibido),e(r.faltante),e(r.responsable||'—'),r.archivos?`<button class="button" data-files="${e(r.id)}">Ver (${e(r.archivos)})</button>`:'—']));root.querySelectorAll('[data-files]').forEach(button=>button.onclick=()=>showFiles(button.dataset.files));}
 async function showFiles(id){try{const {data,error}=await supabase.from('recepcion_archivos').select('ruta,nombre,tipo').eq('recepcion_id',id).order('created_at');if(error)throw error;if(!data?.length){notice('Esta recepción no tiene archivos adjuntos.',true);return;}const links=[];for(const file of data){const signed=await supabase.storage.from('documentos-recepcion').createSignedUrl(file.ruta,3600);if(signed.error)throw signed.error;links.push(`<li><a href="${e(signed.data.signedUrl)}" target="_blank" rel="noopener">${e(file.nombre)}</a></li>`);}const dialog=document.getElementById('editor');document.getElementById('editor-title').textContent='Archivos de la recepción';document.getElementById('editor-fields').innerHTML=`<ul class="file-list">${links.join('')}</ul>`;document.getElementById('editor-error').textContent='';document.getElementById('save-editor').hidden=true;document.getElementById('cancel-editor').textContent='Cerrar';document.getElementById('close-editor').onclick=()=>{dialog.close();document.getElementById('save-editor').hidden=false;document.getElementById('cancel-editor').textContent='Cancelar';};document.getElementById('cancel-editor').onclick=document.getElementById('close-editor').onclick;dialog.showModal();}catch(error){notice(error.message||'No se pudieron abrir los archivos.',true);}}
 async function refresh(){try{[providers,products,sites,lots]=await Promise.all([allRows('proveedores'),allRows('productos'),allRows('sedes'),allRows('lotes')]);rows=await rpc('app_listar_recepciones');render();loadError(null);}catch(error){loadError(error);}}
 function line(i,required=false){return '<div class="reception-line">'+field('producto_'+i,'Producto',{required,choices:options(products.filter(p=>p.estado))})+field('lote_'+i,'Lote',{required,choices:options(lots)})+field('facturada_'+i,'Facturada',{type:'number',required,min:required?0.001:0,step:'0.001'})+field('recibida_'+i,'Recibida',{type:'number',required,min:0,step:'0.001'})+field('unidad_'+i,'Unidad',{required,value:'unidad'})+'</div>';}
 function openReception(){
  const lines=[0,1,2,3,4].map(i=>line(i,i===0)).join('');
  openEditor({title:'Nueva recepción',fields:field('proveedor_id','Proveedor',{required:true,choices:options(providers.filter(p=>p.estado))})+field('tipo_comprobante','Comprobante',{choices:'<option>Factura</option><option>Boleta</option><option>Guía</option><option>Nota de crédito</option>'})+field('serie','Serie',{required:true,maxLength:10})+field('numero','Número',{required:true,maxLength:30})+field('fecha_emision','Fecha de emisión',{type:'date',required:true,value:new Date().toISOString().slice(0,10)})+field('sede_id','Sede de destino',{required:true,choices:options(sites.filter(s=>s.estado))})+field('responsable','Responsable de recepción',{required:true,maxLength:150})+'<p class="muted full-width">Agrega hasta cinco productos de la misma factura. Deja las líneas restantes vacías.</p>'+lines+field('observaciones','Observaciones',{type:'textarea',maxLength:1000})+'<label class="field full-width">Fotos o PDF de la factura<input name="archivos" type="file" accept="image/jpeg,image/png,application/pdf" multiple><small>Máximo 10 MB por imagen y 15 MB por PDF.</small></label>',
   save:async values=>{
    const detalles=[];for(let i=0;i<5;i++){const p=values['producto_'+i];if(!p)continue;const f=Number(values['facturada_'+i]),r=Number(values['recibida_'+i]);if(!values['lote_'+i]||!values['unidad_'+i]||!Number.isFinite(f)||!Number.isFinite(r)||f<=0||r<0||r>f)throw new Error('Revisa producto, lote y cantidades.');detalles.push({producto_id:p,lote_id:values['lote_'+i],cantidad_facturada:f,cantidad_recibida:r,unidad:values['unidad_'+i].trim()});}
    if(!detalles.length)throw new Error('Agrega al menos un producto.');
    const rid=await rpc('app_registrar_recepcion',{p_recepcion:{proveedor_id:values.proveedor_id,tipo_comprobante:values.tipo_comprobante,serie:values.serie.trim(),numero:values.numero.trim(),fecha_emision:values.fecha_emision,sede_id:values.sede_id,responsable:values.responsable.trim(),observaciones:values.observaciones||'',detalles}});
    const files=values.__form.elements.archivos.files;for(const file of files){const max=file.type==='application/pdf'?15:10;if(file.size>max*1024*1024)throw new Error('Un archivo supera el límite permitido.');const path=`${rid}/${crypto.randomUUID()}-${file.name.replace(/[^a-zA-Z0-9._-]/g,'_')}`;const upload=await supabase.storage.from('documentos-recepcion').upload(path,file,{upsert:false,contentType:file.type});if(upload.error)throw upload.error;const saved=await supabase.from('recepcion_archivos').insert({recepcion_id:rid,ruta:path,nombre:file.name,tipo:file.type,tamano:file.size});if(saved.error)throw saved.error;}
    notice('Recepción guardada; el inventario aumentó con lo recibido.');await refresh();
   }});
 }
 root.querySelector('#new-reception')?.addEventListener('click',openReception);root.querySelector('#refresh').onclick=refresh;await refresh();return {refresh,tables:['recepciones','recepcion_detalles','recepcion_archivos','inventario','movimientos','productos','proveedores','sedes','lotes']};
}
