begin;
create table if not exists public.recepciones(id uuid primary key default gen_random_uuid(),proveedor_id uuid not null references public.proveedores(id),tipo_comprobante text not null default 'Factura',serie text not null,numero text not null,fecha_emision date not null,sede_id uuid not null references public.sedes(id),responsable text not null,observaciones text,created_at timestamptz not null default now(),created_by uuid references auth.users(id),unique(proveedor_id,tipo_comprobante,serie,numero));
create table if not exists public.recepcion_detalles(id uuid primary key default gen_random_uuid(),recepcion_id uuid not null references public.recepciones(id) on delete cascade,producto_id uuid not null references public.productos(id),lote_id uuid not null references public.lotes(id),cantidad_facturada numeric(18,3) not null check(cantidad_facturada>0),cantidad_recibida numeric(18,3) not null check(cantidad_recibida>=0 and cantidad_recibida<=cantidad_facturada),unidad text not null,created_at timestamptz not null default now());
alter table public.recepciones enable row level security;alter table public.recepcion_detalles enable row level security;revoke all on public.recepciones,public.recepcion_detalles from public,anon,authenticated;grant select on public.recepciones,public.recepcion_detalles to authenticated;
create policy recepciones_read on public.recepciones for select to authenticated using(public.app_rol() is not null);create policy recepcion_detalles_read on public.recepcion_detalles for select to authenticated using(public.app_rol() is not null);
create or replace function public.app_registrar_recepcion(p_recepcion jsonb) returns uuid language plpgsql security definer set search_path='' as $$
declare r jsonb:=p_recepcion; rid uuid; d jsonb; prod uuid; lot uuid; received numeric; op uuid;
begin
 if coalesce(public.app_rol(),'') not in ('administrador','operador') then raise exception 'No tienes permiso para registrar recepciones.'; end if;
 insert into public.recepciones(proveedor_id,tipo_comprobante,serie,numero,fecha_emision,sede_id,responsable,observaciones,created_by) values((r->>'proveedor_id')::uuid,coalesce(r->>'tipo_comprobante','Factura'),btrim(r->>'serie'),btrim(r->>'numero'),(r->>'fecha_emision')::date,(r->>'sede_id')::uuid,btrim(r->>'responsable'),nullif(btrim(r->>'observaciones'),''),auth.uid()) returning id into rid;
 for d in select * from jsonb_array_elements(r->'detalles') loop
  prod:=(d->>'producto_id')::uuid;lot:=(d->>'lote_id')::uuid;received:=(d->>'cantidad_recibida')::numeric;
  insert into public.recepcion_detalles(recepcion_id,producto_id,lote_id,cantidad_facturada,cantidad_recibida,unidad) values(rid,prod,lot,(d->>'cantidad_facturada')::numeric,received,btrim(d->>'unidad'));
  if received>0 then op:=gen_random_uuid();perform public.app_registrar_movimiento(op,'entrada',prod,lot,(r->>'sede_id')::text,null,received,concat(r->>'tipo_comprobante',' ',r->>'serie','-',r->>'numero'),'Recepción de compra');end if;
 end loop;return rid;
end $$;
create or replace function public.app_listar_recepciones() returns jsonb language sql stable security invoker set search_path='' as $$ select coalesce(jsonb_agg(to_jsonb(x) order by x.fecha_emision desc),'[]'::jsonb) from (select r.fecha_emision,p.nombre proveedor,r.tipo_comprobante,r.serie,r.numero,s.nombre sede,d.producto_id,pr.nombre producto,d.cantidad_facturada,d.cantidad_recibida,d.cantidad_facturada-d.cantidad_recibida faltante,d.unidad,r.responsable from public.recepciones r join public.proveedores p on p.id=r.proveedor_id join public.sedes s on s.id=r.sede_id join public.recepcion_detalles d on d.recepcion_id=r.id join public.productos pr on pr.id=d.producto_id) x $$;
revoke all on function public.app_registrar_recepcion(jsonb),public.app_listar_recepciones() from public,anon,authenticated;grant execute on function public.app_registrar_recepcion(jsonb),public.app_listar_recepciones() to authenticated;commit;
