begin;
create table if not exists public.recepciones(id uuid primary key default gen_random_uuid(),proveedor_id bigint not null references public.proveedores(id),tipo_comprobante text not null default 'Factura',serie text not null,numero text not null,fecha_emision date not null,sede_id bigint not null references public.sedes(id),responsable text not null,observaciones text,created_at timestamptz not null default now(),created_by uuid references auth.users(id),unique(proveedor_id,tipo_comprobante,serie,numero));
create table if not exists public.recepcion_detalles(id uuid primary key default gen_random_uuid(),recepcion_id uuid not null references public.recepciones(id) on delete cascade,producto_id bigint not null references public.productos(id),lote_id uuid not null references public.lotes(id),cantidad_facturada numeric(18,3) not null check(cantidad_facturada>0),cantidad_recibida numeric(18,3) not null check(cantidad_recibida>=0 and cantidad_recibida<=cantidad_facturada),unidad text not null,created_at timestamptz not null default now());
create table if not exists public.recepcion_archivos(id uuid primary key default gen_random_uuid(),recepcion_id uuid not null references public.recepciones(id) on delete cascade,ruta text not null,nombre text not null,tipo text not null,tamano bigint not null check(tamano>0),created_at timestamptz not null default now(),created_by uuid references auth.users(id));
alter table public.recepciones enable row level security;alter table public.recepcion_detalles enable row level security;alter table public.recepcion_archivos enable row level security;revoke all on public.recepciones,public.recepcion_detalles,public.recepcion_archivos from public,anon,authenticated;grant select on public.recepciones,public.recepcion_detalles,public.recepcion_archivos to authenticated;grant insert on public.recepcion_archivos to authenticated;
drop policy if exists recepciones_read on public.recepciones;drop policy if exists recepcion_detalles_read on public.recepcion_detalles;drop policy if exists recepcion_archivos_read on public.recepcion_archivos;
create policy recepciones_read on public.recepciones for select to authenticated using(public.app_rol() is not null);create policy recepcion_detalles_read on public.recepcion_detalles for select to authenticated using(public.app_rol() is not null);create policy recepcion_archivos_read on public.recepcion_archivos for select to authenticated using(public.app_rol() is not null);create policy recepcion_archivos_insert on public.recepcion_archivos for insert to authenticated with check(public.app_rol() is not null and (created_by is null or created_by=auth.uid()));
create or replace function public.app_registrar_recepcion(p_recepcion jsonb) returns uuid language plpgsql security definer set search_path='' as $$
declare r jsonb:=p_recepcion; rid uuid; d jsonb; prod bigint; lot uuid; received numeric; op uuid;
begin
 if coalesce(public.app_rol(),'') not in ('administrador','operador') then raise exception 'No tienes permiso para registrar recepciones.'; end if;
 insert into public.recepciones(proveedor_id,tipo_comprobante,serie,numero,fecha_emision,sede_id,responsable,observaciones,created_by) values((r->>'proveedor_id')::bigint,coalesce(r->>'tipo_comprobante','Factura'),btrim(r->>'serie'),btrim(r->>'numero'),(r->>'fecha_emision')::date,(r->>'sede_id')::bigint,btrim(r->>'responsable'),nullif(btrim(r->>'observaciones'),''),auth.uid()) returning id into rid;
 for d in select * from jsonb_array_elements(r->'detalles') loop
  prod:=(d->>'producto_id')::bigint;lot:=(d->>'lote_id')::uuid;received:=(d->>'cantidad_recibida')::numeric;
  insert into public.recepcion_detalles(recepcion_id,producto_id,lote_id,cantidad_facturada,cantidad_recibida,unidad) values(rid,prod,lot,(d->>'cantidad_facturada')::numeric,received,btrim(d->>'unidad'));
  if received>0 then op:=gen_random_uuid();perform public.app_registrar_movimiento(op,'entrada',prod::text,lot,(r->>'sede_id')::text,null,received,concat(r->>'tipo_comprobante',' ',r->>'serie','-',r->>'numero'),'Recepción de compra');end if;
 end loop;return rid;
end $$;
create or replace function public.app_listar_recepciones() returns jsonb language sql stable security invoker set search_path='' as $$ select coalesce(jsonb_agg(to_jsonb(x) order by x.fecha_emision desc),'[]'::jsonb) from (select r.id,r.fecha_emision,p.nombre proveedor,r.tipo_comprobante,r.serie,r.numero,s.nombre sede,string_agg(distinct pr.nombre, ', ' order by pr.nombre) productos,coalesce(sum(d.cantidad_facturada),0) facturado,coalesce(sum(d.cantidad_recibida),0) recibido,coalesce(sum(d.cantidad_facturada-d.cantidad_recibida),0) faltante,r.responsable,(select count(*) from public.recepcion_archivos a where a.recepcion_id=r.id) archivos from public.recepciones r join public.proveedores p on p.id=r.proveedor_id join public.sedes s on s.id=r.sede_id join public.recepcion_detalles d on d.recepcion_id=r.id join public.productos pr on pr.id=d.producto_id group by r.id,r.fecha_emision,p.nombre,r.tipo_comprobante,r.serie,r.numero,s.nombre,r.responsable) x $$;
revoke all on function public.app_registrar_recepcion(jsonb),public.app_listar_recepciones() from public,anon,authenticated;grant execute on function public.app_registrar_recepcion(jsonb),public.app_listar_recepciones() to authenticated;commit;
